version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
multi-ecosystem-groups:
  avhengigheter:
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "avhengigheter"
    patterns: ["*"]
    cooldown:
      default-days: 7
      exclude:
        - "navikt/sykepenger-github-workflows*"

  - package-ecosystem: "gradle"
    directory: "/"
    multi-ecosystem-group: "avhengigheter"
    patterns: ["*"]
    cooldown:
      default-days: 7
      exclude:
        - "no.nav.sykepenger.*"
        - "com.github.navikt.tbd-libs:*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    multi-ecosystem-group: "avhengigheter"
    patterns: ["*"]
    registries: "*"
    cooldown:
      default-days: 7
