apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkiv-subsumsjon
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 15
  preStopHook:
    http:
      path: /stop
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 640Mi
    requests:
      cpu: 20m
      memory: 512Mi
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-custom-1-3840
        databases:
          - name: sparkiv-subsumsjon
