name: Bygg og deploy app

on:
    push:
        branches:
            - main

jobs:
    build:
        permissions:
            contents: read
            id-token: write
        name: Bygg image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Test og bygg
              run: ./gradlew build
              env:
                  ORG_GRADLE_PROJECT_githubUser: x-access-token
                  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

            - name: Lag Docker image
              uses: nais/docker-build-push@v0
              id: docker-build-push
              env:
                  TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
              with:
                  team: tbd
                  cache_from: type=gha
                  cache_to: type=gha,mode=max
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}

    deployDev:
        name: Deploy to dev
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: deploy/dev.yml
                  IMAGE: ${{ needs.build.outputs.image }}
